name: TheBuildingGame
version: 1.0
description: 'SethBling''s ''The Building Game'' - optimized for Bukkit!'
depend: [StBukkitLib, WorldEdit, WorldGuard]
softdepend: []
author: Stealth2800
website: http://stealthyone.com/
main: com.stealthyone.mcb.thebuildinggame.TheBuildingGame
commands:
  thebuildinggame:
    description: 'Base plugin command'
    aliases: [bg, tbg, buildinggame]
  guess:
    description: 'Base guess command'
    aliases: [bgguess]
  think:
    description: 'Base think command'
    aliases: [bgthink]