name: TheBuildingGame
version: 1.1.1
description: 'SethBling''s ''The Building Game'' - optimized for Bukkit!'
depend: [StBukkitLib, WorldEdit, WorldGuard]
author: Stealth2800
website: http://stealthyone.com/bukkit
main: com.stealthyone.mcb.thebuildinggame.TheBuildingGame
commands:
  thebuildinggame:
    description: 'Base plugin command'
    aliases: [bg, tbg, buildinggame]